### ISSUE TITLE
Unintended object inference

### ISSUE THREAD

**Issue by JohSand** [fsprojects/FSharp.Control.TaskSeq#256]
Binding task-likes in the taskSeq-builder will trigger the FS3559-warning. This seems to be due to  the existence of the 'TOverall parameter here:
```
        [<NoEagerConstraintApplication>]
        member inline Bind< ^TaskLike, 'T, 'U, ^Awaiter, 'TOverall> :
            task: ^TaskLike * continuation: ('T -> ResumableTSC<'U>) -> ResumableTSC<'U>
                when ^TaskLike: (member GetAwaiter: unit -> ^Awaiter)
                and ^Awaiter :> ICriticalNotifyCompletion
                and ^Awaiter: (member get_IsCompleted: unit -> bool)
                and ^Awaiter: (member GetResult: unit -> 'T)
 ```
This parameter cannot be inferred, since it is not used in the method, and is probably only present due to copy-paste.

**Comment by abelbraaksma** [comment]
Hi @JohSand, thanks for reporting this. The `'TOverall` cannot be removed here. Do you happen to have a small repo for this?

To be fair, when designing this, I didn't expect task-like types to be used very often and I don't think I have proper coverage in the tests (that's should ring some alarm bells, lol). 

I'm glad there are use-cases "in the wild" :) and I hope there's a straightforward fix :).

**Comment by JohSand** [comment]
Hi.
For a repro, the easiest way is to bind Task.Yield(), which does in fact not return a Task, but a YieldAwatable.

So with <WarnOn>FS3559</WarnOn>, I can repro it with code like

`
    taskSeq {
        do! Task.Yield()
        yield 1
    }
`

I can also confirm that remove 'TOverall removes the warning.

**Comment by abelbraaksma** [comment]
Awesome. I'll add a few tests tomorrow and merge the PR. Thanks you very much for reporting this!
