### ISSUE TITLE
Should we throw an exception for TaskSeq.zip when the sequences are of unequal length?

### ISSUE THREAD

**Issue by abelbraaksma** [fsprojects/FSharp.Control.TaskSeq#32]
While writing tests for #31, I started pondering this ☝️.

For comparison, F# throws an `ArgumentException` for `Array.zip` and `List.zip`, but not for `Seq.zip`. Most likely, this is because "getting the next item" can have an unwanted side effect, so instead, they choose to stop processing as soon as one of the sequences is exhausted.

Arguably, such side effect can still happen. I.e., for `zip` we have to call `MoveNextAsync`, which will give us a `bool` that tells us whether we reached the end of the sequence. But, if the first sequence still has items, but the second sequence is exhausted, the side effect of the first sequence for "one item past the last" has already happened.

In fact, I think the `Seq.zip` in F# should probably come with a warning. What if each item is "getting a web page of several megabytes"? AFAIK, there's no `peek` function that would potentially tell me, without side effects, that a sequence is exhausted.

Edit: linking the discussion in the F# repo: https://github.com/dotnet/fsharp/issues/14121

**Comment by abelbraaksma** [comment]
Of relevance, for infinite sequences, this example is relevant: https://stackoverflow.com/questions/7226004/seq-zip-in-f-may-require-seemingly-extra-sequence-element-to-complete.

Basically: if you have an infinite sequence, and you have a filter that returns only two elements of the infinite set, then, combining that with another sequence using `zip`, `map2`, `iter2` and their variants, _will always blow up_! 

The cause being: we need to "peek", and (at least one of) the sequence(s) will try to `MoveNext`, but since no other element in the infinite sequence yields a proper result, we will run forever.

Currently, the way this is implemented in F# is such that it is deterministic: if one of the two sequences exhibits this behavior (i.e. `MoveNext` not finding the "next" item, ever), the combination of the two will run forever.

**Comment by gusty** [comment]
I would definitely align with the mechanism for `Seq.zip`.
IMHO the fact that it hangs in that specific situation is a corner case, which normally is not encountered in the wild, as doing a filter like that is an unsafe operation.

**Comment by abelbraaksma** [comment]
I’m considering adding a shadowed function set that can be opened, that have an overload that takes a `CancelationToken`. This would not be specifically for infinite sequences, but everything here is `async`, so it makes sense to make them cancelable.

I’m still a little on the fence about parity with F#. They made a mistake (IMO) by not having the same behaviour for all collection types (where that makes sense and doesn’t require potential extra side effects). But there’s also the “principle of least surprise”. Hmm, yeah, ultimately I guess I have to bite the bullet and go for parity.

**Comment by gusty** [comment]
I agree in that they made a mistake, but to me the mistake was on `List` and `Array`, while `seq` has the right behavior.

Of interest, in F#+ there is `*.zipShortest` defined for List and arrays.

**Comment by abelbraaksma** [comment]
I agree with you there. I mean: the different collections should have parity in behaviour. Bit if you can get away without exceptions it’s generally better, but then that should have applied to all of them.

**Comment by abelbraaksma** [comment]
This has now been solved in #102.
