### ISSUE TITLE
Interoperating with existing F# async

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FSharp.Control.TaskSeq#79]
We could allow binding to an existing F# Async, passing the cancellation token through.  

Similar to this in the existing AsyncSeq: https://github.com/fsprojects/FSharp.Control.AsyncSeq/blob/main/src/FSharp.Control.AsyncSeq/AsyncSeq.fs#L425

**Comment by abelbraaksma** [comment]
See #110 for a first attempt at this.

**Comment by abelbraaksma** [comment]
This has now been implemented and will be part of the 0.4.0 release cycle.
